# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTENT_TYPE: 'multipart/form-data'
  TOKEN: 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20uc21hcnRiZWFyLmN1Y3VtYmVyIiwiYXVkIjoiY2kiLCJjb250ZXh0Ijp7ImxpdmluZ19kb2NfaWQiOjIyNjV9LCJpYXQiOjE2MzEwMDQwNzJ9.o1V7dpuhJbFUAV8ZHQUjGgYXZAKx_zvvURzJkVPrihY'
  API: '73aa838ef039a79e514c5210b835a489a2783242'
  ZephyUrl: 'https://qademo22.yourzephyr.com'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Cucumber Code
        uses: actions/checkout@v2
        with:
          repository: 'govind1072/cucumber-demo'
          ref: main
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Test
        run: mvn clean test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
          -H "authorization: Bearer ${{ env.TOKEN }}" \
          -H 'content-type: multipart/form-data' \
          -F results_file=@target/cucumber-reports/Cucumber.json \
          -F language=jvm

  Start-Docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: Start Docker
        run: |
          docker container run -d --name zbot70 -v /github/workspace/target/zephyr.xml:"/usr/src/app/zephyr.xml" -e "SERVERURL=https://qademo22.yourzephyr.com" -e "ZBOTNAME=Github" -e "APITOKEN=73aa838ef039a79e514c5210b835a489a2783242" zsdockerbuild/zsdockerimage:zbot70

      # Runs a set of commands using the runners shell
      - name: Run the Vortex Create Job
        run: | 
          abc=$( curl -u test.manager:test.manager POST  https://qademo22.yourzephyr.com/flex/services/rest/v3/automation/job/detail -H 'Content-Type: application/json' -d '{"resultPath":"/usr/src/app/zephyr.xml","zbotAgentMachine":"Github ( 127.0.0.1 )","cycleEndDateStr":"09/30/2021","cycleStartDateStr":"09/01/2021","isDateStr":true,"cycleName":"Github_Action","testRepositoryPath":"Release 1.0 > Node1","assignResultsTo":"-10","isReuse":true,"jobName":"GitHub_Job","jobDescription":"","automationFramework":"JUnit","projectId":1,"releaseId":1,"jobDetailTcrCatalogTreeId":1,"phaseName":"Node1"}' | jq '.id' )
          echo "::set-output name=id::$abc"
          echo ${{ id }}
       
