# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONTENT_TYPE: 'multipart/form-data'
  TOKEN: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20uc21hcnRiZWFyLmN1Y3VtYmVyIiwiYXVkIjoiY2kiLCJjb250ZXh0Ijp7ImxpdmluZ19kb2NfaWQiOjIyNjV9LCJpYXQiOjE2MzEwMDQwNzJ9.o1V7dpuhJbFUAV8ZHQUjGgYXZAKx_zvvURzJkVPrihY'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Cucumber Code
        uses: actions/checkout@v2
        with:
          repository: 'govind1072/cucumber-demo'
          ref: main
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Test
        run: mvn clean test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: curl -X POST https://c4j.cucumber.io/ci/rest/api/results
        -H 'authorization: ${{ env.TOKEN }}'
        -H 'content-type: ${{ env.CONTENT_TYPE }}'
        -F results_file=cucumber-reports/Cucumber.json
        -F language=jvm
